Drop the WageVerification class and associated items
usdigitalresponse/papua-id-demo pull request #44
Opened 2020-09-22 15:50 UTC by smedberg

As discussed at https://usdrcovid19.slack.com/archives/C01874U5PDH/p1600788373017400

2020-09-22 15:53 UTC, MatthewSchultz requested changes
Also remove from `routes.rb`?

2020-09-22 15:54 UTC, smedberg commented
Good call on `routes.rb`- will remove now

2020-09-22 16:04 UTC, smedberg commented
@MatthewSchultz Removed from `routes.rb`, and from a bunch of views, etc.  It kinda had it's hooks in a lot of places.  The app starts and seems to work to me, though I don't know how to test it thoroughly.

2020-09-23 15:51 UTC, MatthewSchultz requested changes
One quick change then is ready.

2020-09-24 15:24 UTC, smedberg commented on db/seeds.rb
> +FactoryBot.create_list(:applicant, 20)
@MatthewSchultz  Sorry, I don't think I understand what you're proposing.  If I revert the change to line 12, seeding doesn't work:
```
smedberg@MES-DESKTOP:~/code/papua-id-demo$ rake db:seed
rake aborted!
NameError: uninitialized constant WageVerification
```

My understanding is that adding `:with_wage_verification` means "fill in the WageVerification objects for these applicants."  But the purpose of this PR is to delete the `WageVerification` class, so I don't think that will work.

Am I misunderstanding?

2020-09-25 19:10 UTC, MatthewSchultz commented on db/seeds.rb
> +FactoryBot.create_list(:applicant, 20)
you're right - if we are going to delete this class, we can't still have this.....

2020-09-25 19:22 UTC, MatthewSchultz commented on db/seeds.rb
> +FactoryBot.create_list(:applicant, 20)
I wanted to make sure this didn't break `/admin/applicants/:id` - and it doesn't. PR approved as is.
![image](https://user-images.githubusercontent.com/173679/94307505-8ef79e00-ff3a-11ea-8cd2-00a4aff31e0a.png)

2020-09-25 19:23 UTC, MatthewSchultz approved these changes

2020-09-25 19:23 UTC, merged